apiVersion: v1
kind: Service
metadata:
  name: remote-service
  namespace: remote-patient
spec:
  selector:
    app: remote
  ports:c
    - protocol: TCP
      port: 3009
      targetPort: 3009
  type: ClusterIP  
