apiVersion: v1
kind: Secret
metadata:
  name: remote-secrets
  namespace: remote-patient
data:
  DB_USER: cG9zdGdyZXM=  # Base64 encoded value of "postgres"
  DB_PASSWORD: MDAwMA==   # Base64 encoded value of "0000"
  DB_NAME: cmVtb3RlTW9ub3RvcmluZw==  # Base64 encoded value of "remoteMonotoring"
  DB_HOST: cG9zdGdyZXItc2VydmljZS5yZW1vdGUtcGF0aWVudC5zdmMuY2x1c3Rlci5sb2NhbA==  # Base64 encoded value of "postgres-service.remote-patient.svc.cluster.local"
